/**
 * TaxiDetails.WebApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Driver } from './driver';


export interface Car { 
    id?: number;
    plate?: string | null;
    model?: string | null;
    color?: string | null;
    assignedDriver: Driver;
}

