/**
 * TaxiDetails.WebApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Data transfer object for user information.
 */
export interface UserDto { 
    /**
     * number phone
     */
    phone: string;
    /**
     * fullname client
     */
    fullName: string;
}

